name: Build ifheif

on:
  push:
  

jobs:
  msvc-build:
    strategy:
      matrix:
        config:
          - { ext: spi, arch: x86, archive: ifheif_x86 }
          - { ext: sph, arch: x64, archive: ifheif_x64 }
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - uses: actions/setup-python@v7

    - name: Install Meson and Ninja
      run: |
        python -m pip install --upgrade pip
        pip install meson ninja
      
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.config.arch }}
    
    - name: Install dav1d
      shell: pwsh
      run: |
        cd ${{ github.workspace }}
        git clone https://code.videolan.org/videolan/dav1d.git -b 1.5.4 --depth 1
        cd dav1d
        meson setup --prefix="${HOME}/dec" --buildtype release --default-library=static -Db_vscrt=mt build
        ninja -C build
        ninja install -C build

    - name: Install libde265
      shell: pwsh
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/strukturag/libde265.git -b v1.1.0 --depth 1
        cd libde265
        cmake -B build -G Ninja --preset=release -DBUILD_SHARED_LIBS=OFF -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_INSTALL_PREFIX="${HOME}/dec" .
        cmake --build build --config Release --parallel
        cmake --install build --config Release

    - name: Install libheif
      shell: pwsh
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/strukturag/libheif.git -b v1.23.2 --depth 1
        cd libheif
        $Env:CMAKE_PREFIX_PATH="${HOME}/dec"
        cmake -B build -G Ninja --preset=release -DBUILD_SHARED_LIBS=OFF -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DBUILD_DOCUMENTATION=OFF -DWITH_EXAMPLES=OFF -DWITH_GDK_PIXBUF=OFF -DENABLE_PLUGIN_LOADING=OFF -DWITH_HEADER_COMPRESSION=OFF -DWITH_UNCOMPRESSED_CODEC=OFF -DCMAKE_INSTALL_PREFIX="${HOME}/dec" -DCMAKE_CXX_FLAGS="/DLIBDE265_STATIC_BUILD" -DCMAKE_C_FLAGS="/DLIBDE265_STATIC_BUILD"  .
        cmake --build build --config Release --parallel
        cmake --install build --config Release

    - name: Build ifheif
      shell: pwsh
      run: |
        cd ${{ github.workspace }}
        cl src/ifheif.cpp src/ifheif.def /I"${HOME}/dec/include" heif.lib libde265.lib libdav1d.a /MT /LD /DLIBDE265_STATIC_BUILD /DLIBHEIF_STATIC_BUILD /utf-8 /link /OUT:ifheif.${{ matrix.config.ext }} /LIBPATH:"${HOME}/dec/lib"

    - name: Add License Files
      shell: pwsh
      run: |
        cd ${{ github.workspace }}
        mkdir Licenses
        cd Licenses
        cp ../dav1d/COPYING dav1d.txt
        cp ../libde265/COPYING libde265.txt
        cp ../libheif/COPYING libheif.txt

    - name: Create archive
      shell: pwsh
      run: |
        cd ${{ github.workspace }}
        7z a ${{ matrix.config.archive }}.zip "src/*" "Licenses/*" LICENSE Readme.md ifheif.${{ matrix.config.ext }}

    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.config.archive }}
        path: ${{ matrix.config.archive }}.zip

  release:
    needs: msvc-build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - uses: actions/download-artifact@v8
      with:
        path: artifacts

    # https://gist.github.com/superbrothers/af84a2f8af394a62352e06537a640746        
    - name: Create a Release
      shell: pwsh
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ github.workspace }}
        $REVCOUNT=git rev-list --count HEAD
        $RELEASE_NAME="r${REVCOUNT}"
        $TAG_NAME="r${REVCOUNT}"
        mv ./artifacts/*/*.zip ./
        gh release create "${TAG_NAME}" ./*.zip -t "${RELEASE_NAME}"


